# #############################################################################
# Do not delete the `UNIQUE_ID` line below, I use it to backup original files
# so they're not lost when my symlinks are applied
# UNIQUE_ID=do_not_delete_this_line
# #############################################################################

# import = ["~/github/dotfiles-latest/alacritty/themes/dracula/dracula.toml"]
# import = ["~/github/dotfiles-latest/alacritty/themes/catppuccin/catppuccin-mocha.toml"]
# import = ["~/github/dotfiles-latest/alacritty/themes/catppuccin/catppuccin-macchiato.toml"]
# import = ["~/github/dotfiles-latest/alacritty/themes/catppuccin/catppuccin-frappe.toml"]
# import = ["~/github/dotfiles-latest/alacritty/themes/catppuccin/catppuccin-latte.toml"]

[general]
live_config_reload = true


[colors]
draw_bold_text_with_bright_colors = true


[font]
size = 33

[font.normal]
family = "MesloLGS NF"

[scrolling]
# Maximum number of lines in the scrollback buffer.
# Specifying '0' will disable scrolling.
history = 10000
# Scrolling distance multiplier.
multiplier = 3

[shell]
program = "/bin/bash"

[window]
decorations = "None"
opacity = 0.1

# Window padding (changes require restart)
# Blank space added around the window in pixels. This padding is scaled
# by DPI and the specified value is always added at both opposing sides.
[window.padding]
x = 8
y = 8

[window.dimensions]
columns = 185
lines = 40

# I don't need to enable this, as I normally select in visual mode and yank
# But apparently it allows you to copy to clipboard by just selecting the text
# When set to `true`, selected text will be copied to the primary clipboard.
[selection]
save_to_clipboard = true
